import type { Metadata } from "next";
import { ArrowUpRight, Cpu, Layers3, Sparkles } from "lucide-react";
import { PublicSiteShell } from "@/components/public-site-shell";

export const metadata: Metadata = { title: "Grupo Shiftcore | VetorCAD", description: "Conheça o Grupo Shiftcore, responsável pelo desenvolvimento do VetorCAD.", alternates: { canonical: "https://vetorcad.com.br/grupo-shiftcore" } };

const pillars = [
  { icon: Cpu, title: "Engenharia de produto", text: "Construção contínua de software próprio para resolver problemas técnicos reais." },
  { icon: Layers3, title: "Desenvolvimento", text: "Arquiteturas digitais pensadas para unir precisão, escala e uma experiência simples." },
  { icon: Sparkles, title: "Tecnologia aplicada", text: "Inteligência artificial e automação transformadas em recursos úteis para o trabalho." },
];

export default function GrupoShiftcorePage() {
  return <PublicSiteShell><main className="relative overflow-hidden border-b border-[#1c2822] bg-[#070b09]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_10%,rgba(183,243,74,.14),transparent_32%),linear-gradient(135deg,#070b09,#0a1510_52%,#070b09)]" /><div className="absolute left-[8%] top-36 hidden h-48 w-48 rounded-full border border-[#b7f34a]/10 lg:block" /><div className="absolute left-[11%] top-44 hidden h-32 w-32 rounded-full border border-[#b7f34a]/10 lg:block" />
    <section className="relative mx-auto grid max-w-7xl gap-12 px-4 py-20 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:py-28"><div className="admin-card-enter flex flex-col justify-center"><span className="inline-flex w-fit rounded-full border border-[#b7f34a]/35 bg-[#b7f34a]/10 px-3 py-2 text-[10px] font-black uppercase tracking-[.16em] text-[#b7f34a]">Produto desenvolvido pelo Grupo Shiftcore</span><h1 className="mt-7 max-w-3xl text-5xl font-black leading-[1.02] tracking-[-.06em] md:text-7xl">Tecnologia criada para transformar ideias em soluções digitais.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#b8c8c0]">O VetorCAD faz parte do ecossistema de produtos desenvolvidos pelo Grupo Shiftcore, uma empresa focada em software, inteligência artificial e soluções tecnológicas.</p><a href="https://shiftcore.com.br/.br" target="_blank" rel="noreferrer" className="mt-8 inline-flex w-fit items-center gap-3 rounded-2xl bg-[#b7f34a] px-6 py-4 text-sm font-black text-[#07100a] transition hover:-translate-y-0.5 hover:brightness-105">Conhecer Grupo Shiftcore <ArrowUpRight size={17} /></a></div><div className="admin-card-enter relative flex items-center justify-center" style={{ animationDelay: "120ms" }}><div className="relative w-full max-w-md rounded-[2rem] border border-[#304238] bg-[#0d1411]/90 p-6 shadow-2xl shadow-black/30"><div className="absolute -right-3 -top-3 rounded-full border border-[#b7f34a]/40 bg-[#101a14] px-3 py-1 text-[10px] font-black uppercase tracking-[.12em] text-[#b7f34a]">Ecossistema</div><div className="rounded-2xl border border-[#b7f34a]/35 bg-[#b7f34a]/10 p-6 text-center"><div className="text-xs font-black uppercase tracking-[.16em] text-[#b7f34a]">Grupo Shiftcore</div><div className="mt-3 text-sm text-[#c7d4cd]">Visão, engenharia e desenvolvimento</div></div><div className="mx-auto h-12 w-px bg-gradient-to-b from-[#b7f34a] to-transparent" /><div className="rounded-2xl border border-[#304238] bg-[#111915] p-6 text-center"><div className="text-xs font-black uppercase tracking-[.16em] text-[#b7f34a]">Desenvolvimento</div><div className="mt-3 text-sm text-[#c7d4cd]">Produtos digitais próprios</div></div><div className="mx-auto h-12 w-px bg-gradient-to-b from-[#b7f34a] to-transparent" /><div className="rounded-2xl border border-[#b7f34a]/60 bg-[#b7f34a] p-6 text-center text-[#07100a]"><div className="text-xs font-black uppercase tracking-[.16em]">VetorCAD</div><div className="mt-3 text-sm font-bold">Conversão técnica para CAD</div></div></div></div></section>
    <section className="relative mx-auto max-w-7xl px-4 py-16 lg:px-8 lg:py-20"><div className="max-w-3xl"><div className="text-xs font-black uppercase tracking-[.16em] text-[#b7f34a]">Sobre o Grupo Shiftcore</div><h2 className="mt-4 text-3xl font-black tracking-[-.04em] md:text-5xl">Produtos digitais com precisão e propósito.</h2><p className="mt-5 text-lg leading-8 text-[#b8c8c0]">O Grupo Shiftcore desenvolve produtos digitais próprios combinando engenharia, tecnologia e inteligência artificial para criar soluções eficientes e inovadoras.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{pillars.map(({ icon: Icon, title, text }, index) => <article key={title} className="admin-card-enter rounded-3xl border border-[#304238] bg-[#0d1411] p-6 transition duration-300 hover:-translate-y-1 hover:border-[#b7f34a]/60" style={{ animationDelay: `${index * 100}ms` }}><Icon className="text-[#b7f34a]" size={22} /><h3 className="mt-5 font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-[#9eafa5]">{text}</p></article>)}</div></section>
  </main></PublicSiteShell>;
}
