import type { AcademyModule } from "@/types/academy";

export const VETORCAD_ACADEMY_MODULES: AcademyModule[] = [
  {
    id: "fundamentos-vetorcad",
    sequence: 1,
    code: "01",
    title: "Fundamentos do VetorCAD",
    summary: "Entenda a lógica do workspace, projetos e fluxo técnico da plataforma.",
    steps: [
      {
        id: "fundamentos-interface",
        moduleId: "fundamentos-vetorcad",
        sequence: 1,
        title: "Interface profissional do VetorCAD",
        objective: "Reconhecer as áreas principais do editor e do painel SaaS.",
        description: "Conheça a separação entre projetos, editor CAD, perfil, processamento e exportação para trabalhar com menos tentativa e erro.",
        estimatedMinutes: 4,
        mediaPlaceholder: { type: "video", label: "Vídeo preparado para tour da interface" },
        checklist: ["Identificar painel esquerdo", "Localizar área central de preview", "Localizar exportações e perfil"],
      },
      {
        id: "fundamentos-projeto",
        moduleId: "fundamentos-vetorcad",
        sequence: 2,
        title: "Projetos e persistência",
        objective: "Entender quando um documento está salvo e pronto para continuar depois.",
        description: "Veja como criar projetos, salvar alterações e evitar abrir fluxos avançados antes da persistência ser concluída.",
        estimatedMinutes: 5,
        mediaPlaceholder: { type: "image", label: "Imagem futura do status de salvamento" },
        checklist: ["Criar um projeto", "Verificar status salvo", "Abrir projeto existente"],
      },
    ],
  },
  {
    id: "importacao-arquivos",
    sequence: 2,
    code: "02",
    title: "Importação de arquivos",
    summary: "Prepare imagens e PDFs técnicos para processamento CAD.",
    steps: [
      {
        id: "importacao-formatos",
        moduleId: "importacao-arquivos",
        sequence: 1,
        title: "Formatos aceitos",
        objective: "Escolher o arquivo correto para obter melhor qualidade de vetorização.",
        description: "Entenda quando usar PNG, JPG, WEBP, TIFF ou PDF e como a primeira página do PDF entra no pipeline de imagem.",
        estimatedMinutes: 6,
        mediaPlaceholder: { type: "video", label: "Vídeo preparado sobre upload de imagem e PDF" },
        checklist: ["Identificar formato do arquivo", "Enviar PDF técnico", "Confirmar preview processado"],
      },
      {
        id: "importacao-qualidade",
        moduleId: "importacao-arquivos",
        sequence: 2,
        title: "Qualidade de entrada",
        objective: "Avaliar nitidez, contraste e resolução antes da conversão.",
        description: "Aprenda a reconhecer arquivos adequados para CAD e quando usar melhoria de imagem antes da vetorização.",
        estimatedMinutes: 5,
        mediaPlaceholder: { type: "image", label: "Imagem futura de comparação de qualidade" },
        checklist: ["Conferir linhas finas", "Avaliar contraste", "Usar melhoria quando necessário"],
      },
    ],
  },
  {
    id: "vetorizacao",
    sequence: 3,
    code: "03",
    title: "Vetorização",
    summary: "Transforme imagens técnicas em elementos vetoriais editáveis.",
    steps: [
      {
        id: "vetorizacao-contornos",
        moduleId: "vetorizacao",
        sequence: 1,
        title: "Contornos e precisão",
        objective: "Converter linhas e formas em caminhos vetoriais com controle técnico.",
        description: "Veja como os contornos são extraídos e como ajustes de precisão impactam o resultado final.",
        estimatedMinutes: 7,
        mediaPlaceholder: { type: "video", label: "Vídeo preparado sobre contornos" },
        checklist: ["Gerar contornos", "Comparar preview vetorial", "Ajustar precisão"],
      },
      {
        id: "vetorizacao-limpeza",
        moduleId: "vetorizacao",
        sequence: 2,
        title: "Limpeza de ruído",
        objective: "Reduzir interferências sem perder informação técnica importante.",
        description: "Aprenda a interpretar ruído, linhas quebradas e excesso de pontos durante a conversão.",
        estimatedMinutes: 6,
        mediaPlaceholder: { type: "image", label: "Imagem futura de ruído vs. vetor limpo" },
        checklist: ["Identificar ruídos", "Reprocessar com ajustes", "Validar caminhos gerados"],
      },
    ],
  },
  {
    id: "ajustes-edicao",
    sequence: 4,
    code: "04",
    title: "Ajustes e edição",
    summary: "Revise o resultado e prepare o documento para uso profissional.",
    steps: [
      {
        id: "ajustes-camadas",
        moduleId: "ajustes-edicao",
        sequence: 1,
        title: "Camadas e leitura técnica",
        objective: "Organizar o resultado por camadas e reconhecer informações úteis.",
        description: "Entenda como os dados do documento ajudam a validar o resultado antes da exportação.",
        estimatedMinutes: 5,
        mediaPlaceholder: { type: "video", label: "Vídeo preparado sobre camadas" },
        checklist: ["Abrir layers", "Revisar resumo do vetor", "Checar pontos editáveis"],
      },
    ],
  },
  {
    id: "exportacao-dxf-svg",
    sequence: 5,
    code: "05",
    title: "Exportação DXF/SVG",
    summary: "Gere arquivos compatíveis com CAD, CNC e fluxos técnicos.",
    steps: [
      {
        id: "exportacao-formatos",
        moduleId: "exportacao-dxf-svg",
        sequence: 1,
        title: "Escolhendo DXF ou SVG",
        objective: "Exportar o formato adequado ao seu fluxo profissional.",
        description: "Compare DXF, SVG e PDF visual para escolher a saída correta sem misturar raster e vetor.",
        estimatedMinutes: 6,
        mediaPlaceholder: { type: "video", label: "Vídeo preparado sobre exportações" },
        checklist: ["Exportar SVG", "Exportar DXF", "Validar arquivo gerado"],
      },
    ],
  },
  {
    id: "fluxo-profissional",
    sequence: 6,
    code: "06",
    title: "Fluxo profissional",
    summary: "Combine importação, vetorização, revisão e exportação em uma rotina confiável.",
    steps: [
      {
        id: "fluxo-operacional",
        moduleId: "fluxo-profissional",
        sequence: 1,
        title: "Rotina completa de conversão",
        objective: "Executar um fluxo profissional de ponta a ponta.",
        description: "Consolide os passos anteriores em um processo repetível para plantas, desenhos mecânicos e arquivos de fabricação.",
        estimatedMinutes: 8,
        mediaPlaceholder: { type: "video", label: "Vídeo preparado para fluxo completo" },
        checklist: ["Importar arquivo", "Processar imagem", "Vetorizar", "Exportar resultado"],
      },
    ],
  },
];

export function getAcademySteps() {
  return VETORCAD_ACADEMY_MODULES.flatMap((module) => module.steps);
}
